language: cpp
dist: trusty

install:
  - git fetch --unshallow --tags

matrix:
  include:
  - compiler: gcc
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-multilib

script: make

after_success:
  - cd Installer
  - ./build-server.sh