version: 1.0.0 ci-{build}
os: Visual Studio 2015

configuration:
  - Release

shallow_clone: false

build:
  project: IVN.sln
platform: Win32

artifacts:
  - path: Installer\IVNetwork-*.exe
  - path: Installer\IVNetworkServer-*.exe

after_build:
  - cd Installer
  - build-client.bat
  - build-server.bat

environment:
  UPLOAD_SECRET:
    secure: nnKz9GIcJpS5897d0JeOo0AwfKAOHDzgHCZJdXs1I8gDpKEkQp6LnwDQdJDQnTih
